#!/bin/bash
#

MSG=$(echo $SSH_ORIGINAL_COMMAND|sed 's/notify-send //')
CLEANSTRING=${MSG//[^a-zA-Z0-9_ \.]/}

TORR=$(echo $CLEANSTRING| cut -d " " -f1)

if [[ "$TORR" == "Torrent" ]]; then ICON="--icon=/home/jedjisch/.local/icon/utorrent.png"; fi

DISPLAY=:0 notify-send $ICON "$CLEANSTRING"
