#!/bin/bash
#
########################################################################
#  Client part
#
#  Displays notification sent from server through ssh
#
########################################################################

MSG=$(echo $SSH_ORIGINAL_COMMAND|sed 's/notify-send //')
CLEANSTRING=${MSG//[^a-zA-Z0-9_ ]/}


DISPLAY=:0 notify-send "$CLEANSTRING"

